// Global sample plugin: indexes Start menu shortcuts and launches them on Enter.
// It has no keyword, so whatever the user types is searched here too.

class Shortcut
{
    public string Name = "";
    public string Path = "";
}

List<Shortcut>? cache = null;

List<Shortcut> LoadShortcuts()
{
    var roots = new[]
    {
        Environment.GetFolderPath(Environment.SpecialFolder.StartMenu),
        Environment.GetFolderPath(Environment.SpecialFolder.CommonStartMenu),
        Environment.GetFolderPath(Environment.SpecialFolder.Programs),
        Environment.GetFolderPath(Environment.SpecialFolder.CommonPrograms)
    };

    var found = new Dictionary<string, Shortcut>(StringComparer.OrdinalIgnoreCase);

    foreach (var root in roots.Where(r => !string.IsNullOrEmpty(r) && Directory.Exists(r)))
    {
        IEnumerable<string> files;
        try { files = Directory.EnumerateFiles(root, "*.lnk", SearchOption.AllDirectories); }
        catch { continue; }

        foreach (var file in files)
        {
            var name = Path.GetFileNameWithoutExtension(file);
            if (name.Contains("uninstall", StringComparison.OrdinalIgnoreCase)) continue;

            found.TryAdd(name, new Shortcut { Name = name, Path = file });
        }
    }

    AddStoreApps(found);

    return found.Values.OrderBy(s => s.Name, StringComparer.CurrentCultureIgnoreCase).ToList();
}

// اپ‌های نصب‌شده از استور ویندوز (مثل تلگرام) هیچ .lnk ای نمی‌سازند؛ جایشان shell:AppsFolder با
// شناسه‌ی AUMID است. Get-StartApps همان فهرستی را می‌دهد که استارت‌منو نشان می‌دهد — هم اپ‌های
// معمولی و هم استور. اپ معمولی در AppID مسیر exe یا Microsoft.AutoGenerated دارد؛ اپ استور «!».
// TryAdd یعنی اگر همین نام از .lnk آمده باشد، همان می‌ماند.
void AddStoreApps(Dictionary<string, Shortcut> found)
{
    try
    {
        var psi = new ProcessStartInfo(
            "powershell.exe",
            "-NoProfile -Command \"Get-StartApps | ConvertTo-Json -Compress\"")
        {
            RedirectStandardOutput = true,
            UseShellExecute = false,
            CreateNoWindow = true
        };

        using var process = Process.Start(psi);
        if (process is null) return;

        // اول خواندن، بعد انتظار: اگر خروجی از بافر پایپ بزرگ‌تر باشد، پروسه تا خوانده‌شدن
        // بن‌بست می‌کند و WaitForExit هرگز برنمی‌گردد
        var output = process.StandardOutput.ReadToEnd();
        if (!process.WaitForExit(15000))
        {
            process.Kill();
            return;
        }

        if (string.IsNullOrWhiteSpace(output)) return;

        using var document = System.Text.Json.JsonDocument.Parse(output);
        var items = document.RootElement.ValueKind == System.Text.Json.JsonValueKind.Array
            ? document.RootElement.EnumerateArray().ToList()
            : new List<System.Text.Json.JsonElement> { document.RootElement };

        foreach (var item in items)
        {
            var name = item.TryGetProperty("Name", out var n) ? n.GetString() : null;
            var appId = item.TryGetProperty("AppID", out var a) ? a.GetString() : null;
            if (string.IsNullOrWhiteSpace(name) || string.IsNullOrEmpty(appId) || !appId.Contains('!')) continue;
            if (name.Contains("uninstall", StringComparison.OrdinalIgnoreCase)) continue;

            found.TryAdd(name, new Shortcut { Name = name, Path = "shell:AppsFolder\\" + appId });
        }
    }
    catch
    {
        // فهرست استور مکمل است؛ اگر PowerShell جواب نداد، همان فهرست .lnk باقی می‌ماند
    }
}

int ScoreOf(string name, string term)
{
    if (name.Equals(term, StringComparison.CurrentCultureIgnoreCase)) return 100;
    if (name.StartsWith(term, StringComparison.CurrentCultureIgnoreCase)) return 75;
    if (name.Contains(term, StringComparison.CurrentCultureIgnoreCase)) return 45;

    var initials = string.Concat(name.Split(' ', StringSplitOptions.RemoveEmptyEntries).Select(w => w[0]));
    return initials.StartsWith(term, StringComparison.CurrentCultureIgnoreCase) ? 55 : -1;
}

return Plugin.Create(query =>
{
    var term = query.Search.Trim();
    if (term.Length < 2) return [];

    cache ??= LoadShortcuts();

    return cache
        .Select(s => new { s, score = ScoreOf(s.Name, term) })
        .Where(x => x.score >= 0)
        .OrderByDescending(x => x.score)
        .Take(15)
        .Select(x => new PluginResult
        {
            Id = x.s.Path,
            Title = x.s.Name,
            Subtitle = x.s.Path,
            IconPath = x.s.Path,
            Score = x.score,
            // اپ استور با explorer باز می‌شود؛ .lnk مستقیم
            Action = () =>
            {
                if (x.s.Path.StartsWith("shell:", StringComparison.OrdinalIgnoreCase))
                    Process.Start("explorer.exe", x.s.Path);
                else
                    Process.Start(new ProcessStartInfo(x.s.Path) { UseShellExecute = true });
            }
        });
});
